export { Context } from "./context.js";
export { SystemContext } from "./system-context.js";
export { PluginCatalog, parsePluginYaml, readPluginHeader, readSourceHeader } from "./plugin-catalog.js";
export {
    HOST_ADAPTER_ENV,
    createBrowserHostAdapter,
    getDefaultHostAdapter,
    getHostAdapter,
    setDefaultHostAdapter,
} from "./host-adapter.js";
export {
    EVALUATION_BUDGET_ENV,
    EvaluationLimitError,
    createEvaluationBudget,
    enterEvaluationBudget,
    evaluationCheckpoint,
} from "./evaluation-budget.js";
export {
    RendererRegistry,
    UnsupportedRenderError,
    createRenderResult,
    createRendererCollection,
    createRendererPluginCollection,
    isRenderResult,
    renderResultValue,
} from "./renderer-registry.js";
export { Cell } from "./cell.js";
export {
    OperationalFault,
    TimeoutFault,
    CleanupGraceFault,
    isOperationalFault,
    faultToRixValue,
} from "./operational-fault.js";
export {
    createAsyncStream,
    asyncStreamFromIterable,
    createHotAsyncStream,
    isAsyncStream,
    closeAsyncStream,
    asyncStreamStatus,
    asyncStreamCanCompleteWithoutPull,
} from "./async-stream.js";
export {
    AsyncScheduler,
    registerBackgroundTask,
    drainBackgroundTasks,
    registerAsyncResource,
    unregisterAsyncResource,
    disposeAsyncResources,
} from "./async-runtime.js";
export { createBinding, isBinding } from "./binding.js";
export { createFormulaSheet, isFormulaSheet } from "./formula-sheet.js";
export {
    RIXCEL_FORMAT,
    RIXCEL_VERSION,
    RIXCEL_ASSIGNMENT_MODES,
    appendRixCelEvent,
    clearRixCelDraft,
    createRixCelDocument,
    materializeRixCelDocument,
    parseRixCelDocument,
    exportRixCelDocument,
    rixCelEventCommand,
    setRixCelCursor,
    setRixCelDraft,
    stringifyRixCelDocument,
    importRixCelDocument,
} from "./rixcel-document.js";
export { rewriteRixCelReferences } from "./rixcel-references.js";
export { createLiveView, isLiveView, isReactiveSource } from "./reactive-view.js";
export {
    createReactiveGraph,
    isReactiveGraph,
    isReactiveNode,
    REACTIVE_READ_ENV,
} from "./reactive-graph.js";
export { HOLE, isHole } from "./hole.js";
export { DiagnosticsRegistry, getDiagnostics, RixAbort, isRixAbort, createEvent } from "./diagnostics.js";
export { runtimeDefaults } from "./runtime-config.js";
export {
    REFINEMENT_REQUEST_SCHEMA,
    REFINEMENT_RESULT_SCHEMA,
    REFINEMENT_CAPABILITIES_SCHEMA,
    normalizeRefinementRequest,
    refinementEffectiveLimits,
    refinementSupports,
    checkRefinementResult,
    unsupportedRefinementResult,
    refinementOutcome,
} from "./refinement.js";
export {
    RANGE_EVIDENCE_SCHEMA,
    RANGE_CHECKER_VOCABULARY,
    checkRangeEvidence,
} from "./range-evidence-checker.js";
export {
    CALCULUS_GRAPH_RANGE_SCHEMA,
    CALCULUS_GRAPH_RANGE_CHECKER,
    CALCULUS_GRAPH_SIMPLIFICATION_SCHEMA,
    CALCULUS_GRAPH_SIMPLIFICATION_CHECKER,
    CALCULUS_GRAPH_REWRITE_SCHEMA,
    CALCULUS_GRAPH_REWRITE_CHECKER,
    calculusGraphStructuralKey,
    simplifyCalculusGraph,
    checkCalculusGraphSimplification,
    evaluateCalculusGraphRange,
    checkCalculusGraphRangeResult,
    calculusGraphRangeValue,
    calculusGraphRangeCheckValue,
    recognizeCalculusGraph,
    calculusGraphRecognitionValue,
    calculusGraphSimplificationValue,
    calculusGraphSimplificationCheckValue,
    proposeCalculusGraphRewrite,
    checkCalculusGraphRewrite,
    calculusGraphRewriteValue,
    calculusGraphRewriteCheckValue,
    differentiateCalculusPrimitiveGraphN,
    differentiateCalculusPrimitiveGraph,
    checkCalculusDerivativeTransformation,
    derivativeObligationChecks,
    calculusDerivativeCheckValue,
    CALCULUS_DERIVATIVE_SIGN_SCHEMA,
    evaluateCalculusDerivativeSign,
    calculusDerivativeSignValue,
    CALCULUS_LIPSCHITZ_RANGE_SCHEMA,
    CALCULUS_TAYLOR_RANGE_SCHEMA,
    CALCULUS_STRATEGY_RANGE_CHECKER,
    evaluateCalculusLipschitzRange,
    evaluateCalculusTaylorRange,
    checkCalculusStrategyRangeResult,
    calculusLipschitzRangeValue,
    calculusTaylorRangeValue,
    substituteCalculusGraphVariable,
} from "./calculus-range.js";
export {
    RATIONAL_BOX_SCHEMA,
    MULTIVARIATE_RANGE_REQUEST_SCHEMA,
    JACOBIAN_BOX_RANGE_SCHEMA,
    AFFINE_BOX_RANGE_SCHEMA,
    TAYLOR_MODEL_BOX_RANGE_SCHEMA,
    MULTIVARIATE_RANGE_CHECKER,
    KRAWCZYK_BOX_SCHEMA,
    KRAWCZYK_CHECKER,
    createRationalBox,
    createMultivariateRangeRequest,
    evaluateJacobianBoxRange,
    evaluateAffineBoxRange,
    evaluateTaylorModelBoxRange,
    evaluateKrawczykBox,
    checkKrawczykResult,
    checkMultivariateRangeResult,
    rationalBoxValue,
    multivariateRangeRequestValue,
    jacobianBoxRangeValue,
    affineBoxRangeValue,
    taylorModelBoxRangeValue,
    krawczykBoxValue,
    krawczykCheckValue,
    multivariateRangeCheckValue,
} from "./multivariate-range.js";
export {
    RANGE_SET_INTERCHANGE_VERSION,
    RANGE_SET_STABLE_VERSIONS,
    RangeSetInterchangeVersionError,
    rangeSetMigrationPlan,
} from "./range-set-interchange.js";
export {
    isOutputValue,
    outputValueKind,
    isInlineOutput,
    isBlockOutput,
    formatOutputText,
    renderOutputHtml,
    renderGraphicSvg,
    createSheet,
    createSheetSnapshot,
    createEmphasis,
    createStrong,
    createCode,
    createMath,
    createLink,
    createLineBreak,
    createSection,
    createList,
    createListItem,
    createQuote,
    createCallout,
    createCodeBlock,
    createMathBlock,
    createAsset,
    createImage,
    createAudio,
    createVideo,
    createControlPanelSnapshot,
    serializeControlPanel,
    renderControlPanelStaticHtml,
    renderControlPanelMarkdown,
    createAlgebraOutputCollection,
    createGraphicsOutputCollection,
    createTimelineOutputCollection,
    createControlsOutputCollection,
    createSyntheticDivision,
    createPlotOutputCollection,
    createPolynomialPlot,
    createGroup,
    createTransform,
    createTextMark,
    createRectangle,
    createCircle,
    createDragPoint,
    createGraphicAction,
    createSliderControl,
    createInputControl,
    createChoiceControl,
    createToggleControl,
    createRangeControl,
    createResetControl,
    createActionControl,
    createHoldControl,
    createControlPanel,
    createSnapshots,
    createTimelineTrack,
    createTimelineSequence,
    createTimelineManifest,
    createTimelineRender,
    createClip,
} from "./output.js";
export {
    createLazySequence,
    cloneLazySequence,
    ensureLazyIndex,
    isLazySequence,
    lazyKnownLength,
    materializeLazySequence,
} from "./lazy-sequence.js";
export {
    DEFAULT_RANDOM_SEED,
    RUNTIME_RNG_KEY,
    configureRuntimeRandom,
    createRngImplementation,
    createRuntimeRng,
    runtimeRandom,
    runtimeRandomInfo,
    seedRuntimeRandom,
} from "./random.js";
export {
    applyStructuralBinary,
    applyStructuralPostfix,
    applyStructuralPrefix,
    collapseStructuralValue,
    createStructuralAlgebraProfile,
    createStructuralFunction,
    createStructuralOperatorTable,
    formatStructuralValue,
    inspectStructuralValue,
    interpretStructuralAlgebra,
    isStructuralAlgebra,
    isStructuralForm,
    isStructuralLiteral,
    isStructuralSymbol,
    liftStructuralValue,
    parseStructuralArithmetic,
    resolveStructuralValue,
    simplifyStructuralValue,
    sortedStructuralFreeSymbols,
    structuralForm,
    structuralFreeSymbols,
    structuralLiteral,
    structuralAlgebra,
    structuralSourceSpan,
    structuralSymbol,
    structuralValueToIr,
    tokenizeStructuralArithmetic,
    STRUCTURAL_ALGEBRA_PROFILES,
} from "./structural-arithmetic.js";
export {
    createDefaultUnitCollection,
    createUnit,
    constructQuantity,
    convertQuantity,
    parseUnitExpression,
    isUnitValue,
    isQuantity,
} from "./quantities.js";
export {
    createDefaultExactCollection,
    createDefaultComplexCollection,
    createExactGenerator,
    exactGeneratorFromPolynomial,
    isExactValue,
    complexConjugate,
    complexParts,
    complexFromParts,
    complexNormSquared,
    CAYLEY_INFINITY,
    isCayleyValue,
    isCayleyInfinity,
    exactSquareRoot,
    createCayley,
    cayleyFromCartesian,
    cayleyCartesian,
    addCayley,
    subtractCayley,
    multiplyCayley,
    divideCayley,
    powCayley,
    negateCayley,
    conjugateCayley,
    inverseCayley,
    equalCayley,
} from "./exact-values.js";

export { OUTPUT_DOCUMENT_SCHEMA, encodeOutputJSON, decodeOutputJSON, snapshotOutputDocument } from "./output-json.js";

export { NUMERIC_PRESENTATION_SCHEMA, createNumericPolicy, presentNumericValue, numericFormatter, withNumericPresentation } from "./numeric-presentation.js";
export { INTERVAL_LINEAR_SCHEMA, INTERVAL_NEWTON_BOX_SCHEMA, BOX_SUBDIVISION_SCHEMA, VALIDATED_BOX_CHECKER,
    evaluateIntervalLinearSolve, evaluateIntervalNewtonBox, evaluateBoxSubdivision, resumeBoxSubdivision,
    checkValidatedBoxResult, validatedBoxValue } from "./validated-boxes.js";

export { OUTPUT_BUNDLE_SCHEMA, OUTPUT_ASSET_MANIFEST_SCHEMA, OUTPUT_ASSET_LIMITS, normalizeAssetReference, isExternalAssetReference, createMemoryAssetStore, hashAssetBytes, resolveAssetManifest, bundleOutputDocument, encodeOutputBundle, decodeOutputBundle } from "./output-assets.js";
export { createOutputBundleHost } from "./output-bundle-host.js";

export { PUBLICATION_PLAN_SCHEMA, PUBLICATION_PROJECT_SCHEMA, createPublicationPlan, resolvePublicationPlan, withPublicationPlan, validatePublicationTree, visitPublicationTree, publicationDiagnostics, quartoProjectYaml } from "./publication-plan.js";

export { createPublicationProject, readPublicationProject } from "./publication-project.js";
