export const runtimeDefaults = Object.freeze({
  defaultLoopMax: 10000,
  defaultAsyncConcurrency: 10,
  asyncCleanupGraceMs: 5000,
  defaultConstructorCaptureMode: "deep_copy",
  symbolicAutoSpec: "safe",
  warnings: Object.freeze({
    conversion: false,
    multifunctionConversion: false,
    multifunctionNoPrep: false,
    implicitUnitConversion: false,
    reactiveUntrackedRead: true,
  }),
  scriptPermissionNames: Object.freeze(["IMPORTS", "NET", "FILES", "PLUGINS"]),
  defaultScriptCapabilityPolicy: Object.freeze({
    includeAllFunctions: true,
    permissions: Object.freeze(["IMPORTS"]),
  }),
  capabilityGroups: Object.freeze({
    Output: Object.freeze(["OUT", "BIND", "LIVEVIEW", "TEXT", "PARAGRAPH", "HEADING", "FRAGMENT", "SNAPSHOTS", "TABLE", "GRID", "SHEET", "CONTROLPANEL", "FIGURE", "SLIDE", "SLIDES", "Algebra", "Timeline"]),
    Controls: Object.freeze(["CONTROLPANEL", "Controls"]),
    Graphics: Object.freeze(["Graphics"]),
    Draw: Object.freeze(["draw"]),
    Plot: Object.freeze(["plot"]),
    Core: Object.freeze(["LEN", "FIRST", "LAST", "GETEL", "IRANGE", "IF", "LOOP", "MULTI", "RAND_NAME", "PRINT", "TGEN", "KEYOF", "KEYS", "VALUES"]),
    Arith: Object.freeze(["ADD", "SUB", "MUL", "DIV", "INTDIV", "DIVMOD", "MOD", "POW", "FACTORIAL", "DOUBLEFACTORIAL"]),
    Logic: Object.freeze(["EQ", "NEQ", "LT", "GT", "LTE", "GTE", "AND", "OR", "NOT"]),
    Collections: Object.freeze(["LEN", "FIRST", "LAST", "GETEL", "IRANGE", "MAP", "FILTER", "REDUCE", "TGEN"]),
    Maps: Object.freeze(["MAP", "KEYOF", "KEYS", "VALUES"]),
    Arrays: Object.freeze(["LEN", "FIRST", "LAST", "GETEL", "IRANGE", "MAP", "FILTER", "REDUCE", "TGEN"]),
    Strings: Object.freeze(["UPPER", "SUBSTR", "PRINT"]),
    Imports: Object.freeze(["IMPORTS"]),
    Plugins: Object.freeze(["PLUGINS"]),
    Net: Object.freeze(["NET"]),
    Files: Object.freeze(["FILES"]),
    Units: Object.freeze(["UNITS", "Units", "CONVERTUNIT", "ConvertUnit", "DEFINEUNIT", "DefineUnit"]),
    Exact: Object.freeze(["EXACT", "Exact", "COMPLEX", "Complex", "DEFINEEXACTGENERATOR", "DefineExactGenerator", "exactalgebras"]),
    Symbolic: Object.freeze(["POLY", "DERIV", "INTEGRATE", "TRANSFORM", "SIMPLIFY", "SPEC", "SPECCABILITY", "INSPECTSPEC", "SPECROLES", "SArith"]),
    Notation: Object.freeze(["SArith", "Poly", "NotationParser"]),
    Random: Object.freeze(["RANDOMSEED", "RandomSeed", "RAND_NAME"]),
    RiXCel: Object.freeze(["FORMULASHEET", "REACTIVEGRAPH", "RIXCELEXPORT", "RIXCELIMPORT", "RIXCELIMPORTCSV", "RIXCELIMPORTTSV", "RIXCELEXPORTCSV", "RIXCELEXPORTTSV"]),
  }),
});
