export const runtimeDefaults = Object.freeze({
  defaultLoopMax: 10000,
  defaultConstructorCaptureMode: "deep_copy",
  symbolicAutoSpec: "safe",
  warnings: Object.freeze({
    conversion: false,
    multifunctionConversion: false,
    multifunctionNoPrep: false,
    implicitUnitConversion: false,
  }),
  scriptPermissionNames: Object.freeze(["IMPORTS", "NET", "FILES"]),
  defaultScriptCapabilityPolicy: Object.freeze({
    includeAllFunctions: true,
    permissions: Object.freeze(["IMPORTS"]),
  }),
  capabilityGroups: Object.freeze({
    Output: Object.freeze(["TEXT", "PARAGRAPH", "HEADING", "FRAGMENT", "TABLE", "GRID", "PATH", "GRAPHIC", "FIGURE", "SLIDE", "SLIDES", "ALGEBRA"]),
    Core: Object.freeze(["LEN", "FIRST", "LAST", "GETEL", "IRANGE", "IF", "LOOP", "MULTI", "RAND_NAME", "PRINT", "TGEN", "KEYOF", "KEYS", "VALUES"]),
    Arith: Object.freeze(["ADD", "SUB", "MUL", "DIV", "INTDIV", "MOD", "POW"]),
    Logic: Object.freeze(["EQ", "NEQ", "LT", "GT", "LTE", "GTE", "AND", "OR", "NOT"]),
    Collections: Object.freeze(["LEN", "FIRST", "LAST", "GETEL", "IRANGE", "MAP", "FILTER", "REDUCE", "TGEN"]),
    Maps: Object.freeze(["MAP", "KEYOF", "KEYS", "VALUES"]),
    Arrays: Object.freeze(["LEN", "FIRST", "LAST", "GETEL", "IRANGE", "MAP", "FILTER", "REDUCE", "TGEN"]),
    Strings: Object.freeze(["UPPER", "SUBSTR", "PRINT"]),
    Imports: Object.freeze(["IMPORTS"]),
    Net: Object.freeze(["NET"]),
    Files: Object.freeze(["FILES"]),
    Units: Object.freeze(["UNITS", "Units", "CONVERTUNIT", "ConvertUnit", "DEFINEUNIT", "DefineUnit"]),
    Exact: Object.freeze(["EXACT", "Exact", "COMPLEX", "Complex", "DEFINEEXACTGENERATOR", "DefineExactGenerator"]),
    Symbolic: Object.freeze(["POLY", "DERIV", "INTEGRATE", "TRANSFORM", "SIMPLIFY", "SPEC", "SPECCABILITY", "INSPECTSPEC"]),
    Random: Object.freeze(["RANDOMSEED", "RandomSeed", "RAND_NAME"]),
  }),
});
