export const runtimeDefaults = Object.freeze({
  defaultLoopMax: 10000,
  defaultAsyncConcurrency: 10,
  asyncCleanupGraceMs: 5000,
  editorMaxEvaluationSteps: 250000,
  editorMaxEvaluationTimeMs: 5000,
  defaultConstructorCaptureMode: "deep_copy",
  symbolicAutoSpec: "safe",
  warnings: Object.freeze({
    conversion: false,
    multifunctionConversion: false,
    multifunctionNoPrep: false,
    implicitUnitConversion: false,
    reactiveUntrackedRead: true,
  }),
  scriptPermissionNames: Object.freeze(["IMPORTS", "NET", "FILES", "PLUGINS", "BACKGROUND"]),
  defaultScriptCapabilityPolicy: Object.freeze({
    includeAllFunctions: true,
    permissions: Object.freeze(["IMPORTS"]),
  }),
  capabilityGroups: Object.freeze({
    Output: Object.freeze(["OUT", "BIND", "LIVEVIEW", "TEXT", "PARAGRAPH", "HEADING", "FRAGMENT", "SNAPSHOTS", "TABLE", "GRID", "SHEET", "CONTROLPANEL", "FIGURE", "SLIDE", "SLIDES", "Algebra", "Timeline"]),
    Controls: Object.freeze(["CONTROLPANEL", "Controls"]),
    Graphics: Object.freeze(["Graphics"]),
    Draw: Object.freeze(["draw"]),
    Plot: Object.freeze(["plot"]),
    Core: Object.freeze(["LEN", "FIRST", "LAST", "GETEL", "IRANGE", "IF", "LOOP", "MULTI", "RAND_NAME", "PRINT", "Shaped", "KEYOF", "KEYS", "VALUES", "REGISTERMETHOD", "CertifiedApproximation", "Undecided", "RefinementRequest", "RefinementEffectiveLimits", "RefinementSupports", "RefinementCheck", "RefinementUnsupported", "TypeKnown", "ImmutableValue"]),
    Methods: Object.freeze(["REGISTERMETHOD"]),
    Arith: Object.freeze(["ADD", "SUB", "MUL", "DIV", "INTDIV", "DIVMOD", "MOD", "POW", "FACTORIAL", "DOUBLEFACTORIAL", "RANGE_POLICY", "RANGE_EVIDENCE", "RANGE_ADD", "RANGE_SUBTRACT", "RANGE_MULTIPLY", "RANGE_DIVIDE", "RANGE_NEGATE", "RANGE_ABSOLUTE_VALUE", "RANGE_RECIPROCAL", "RANGE_INTEGER_POWER", "CALCULUS_RANGE", "CALCULUS_RANGE_CHECK", "CALCULUS_RANGE_RECOGNIZE", "CALCULUS_GRAPH_SIMPLIFY", "CALCULUS_GRAPH_SIMPLIFICATION_CHECK", "CALCULUS_DERIVATIVE_CHECK", "CALCULUS_DERIVATIVE_SIGN", "CALCULUS_LIPSCHITZ_RANGE", "CALCULUS_TAYLOR_RANGE"]),
    Logic: Object.freeze(["EQ", "NEQ", "LT", "GT", "LTE", "GTE", "AND", "OR", "NOT", "GUARD_RETURN"]),
    Collections: Object.freeze(["LEN", "FIRST", "LAST", "GETEL", "IRANGE", "MAP", "FILTER", "REDUCE", "Shaped", "Stream"]),
    Async: Object.freeze(["Stream", "Retry"]),
    Background: Object.freeze(["BACKGROUND"]),
    Maps: Object.freeze(["MAP", "KEYOF", "KEYS", "VALUES"]),
    Arrays: Object.freeze(["LEN", "FIRST", "LAST", "GETEL", "IRANGE", "MAP", "FILTER", "REDUCE", "Shaped"]),
    Strings: Object.freeze(["UPPER", "SUBSTR", "PRINT"]),
    Imports: Object.freeze(["IMPORTS"]),
    Plugins: Object.freeze(["PLUGINS"]),
    Net: Object.freeze(["NET"]),
    Files: Object.freeze(["FILES"]),
    Units: Object.freeze(["UNITS", "Units", "CONVERTUNIT", "ConvertUnit", "DEFINEUNIT", "DefineUnit"]),
    Exact: Object.freeze(["EXACT", "Exact", "COMPLEX", "Complex", "DEFINEEXACTGENERATOR", "DefineExactGenerator", "exactalgebras"]),
    Symbolic: Object.freeze(["POLY", "DERIV", "INTEGRATE", "TRANSFORM", "SIMPLIFY", "SPEC", "SPECCABILITY", "INSPECTSPEC", "SPECROLES", "SPECFRACTIONPARTS", "SArith", "ExpressionVariable", "ExpressionConstant", "ExpressionOperation", "ExpressionApply", "IsExpression", "ExpressionKey", "ExpressionHasScopedSymbols", "SameSymbol", "SYMBOL_RETRIEVE", "SYMBOL_DEFINE", "ExpressionDefinition", "ExpressionExpand"]),
    MathematicalContexts: Object.freeze(["MATH_CONTEXT", "BOUND_SYMBOL"]),
    MathematicalSerialization: Object.freeze(["MathEncodeJSON", "MathDecodeJSON", "MathEncodeJSONL", "MathDecodeJSONL"]),
    MathematicalLocalization: Object.freeze(["MathSubstitute", "MathEvaluate"]),
    SymbolicConstants: Object.freeze(["ExpressionConstantInfo", "ExpressionHasExtendedConstants", "ExpressionReal", "ExpressionRefine"]),
    Notation: Object.freeze(["SArith", "Poly", "NotationParser"]),
    Random: Object.freeze(["RNG", "RANDOMSEED", "RandomSeed", "RAND_NAME"]),
    Probability: Object.freeze(["probability"]),
    Graph: Object.freeze(["graph"]),
    Combinatorics: Object.freeze(["combinatorics", "comb"]),
    RiXCel: Object.freeze(["FORMULASHEET", "REACTIVEGRAPH", "RIXCELEXPORT", "RIXCELIMPORT", "RIXCELIMPORTCSV", "RIXCELIMPORTTSV", "RIXCELEXPORTCSV", "RIXCELEXPORTTSV"]),
  }),
});
