// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {rixTokens} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'OQYQROOOOQP'#Cm'#CmO#lQRO'#CnO#sQRO'#CpOOQP'#Cr'#CrO#zQRO'#CqOOQP'#Cl'#ClO$UQRO'#CkO$rQRO'#CkO%iQRO'#CjOOQP'#Ci'#CiQ&TQRO'#CvQYQROOO&]QRO'#CoOOQP,59Y,59YO&hQRO,59YOOQP,59[,59[O&mQRO,59[OOQP'#Ct'#CtOOQP,59],59]O&rQRO,59]OOQP'#Cu'#CuOOQP'#Cy'#CyO'QQRO,59VO'QQRO,59VOYQRO'#CzO'nQRO,59UOOQP'#Cs'#CsOOQP,59b,59bOOQP-E6t-E6tOYQRO'#CwO(YQRO,59ZOOQP1G.t1G.tOOQP1G.v1G.vOYQRO'#CxO&rQRO1G.wOOQP1G.w1G.wOOQP-E6w-E6wO(eQRO1G.qOOQP,59f,59fOOQP-E6x-E6xOOQP,59c,59cOOQP-E6u-E6uOOQP,59d,59dOOQP-E6v-E6vOOQP7+$c7+$c",
  stateData: ")R~OqOSTOS~OPUOQUORUOSUOUUOVUOWUOXUOYUOZWOrPOsPOuQOxROySOzSO{SO|SO}SO!OSO!PSO!QSO!RSO!SSO!TSO!USO!VSO!WSO!XSO!YSO!ZSO![SO!]SO!^SO!_SO!`SO~Ot^O~PYOw`O~PYO!bbO!cbO~PYOZ_Xo_Xv_X!a_Xt_Xw_X!b_X!c_X~P!OOPUOQUORUOSUOUUOVUOWUOXUOYUOrPOsPO~P!OOZiOo^Xv^X!a^Xt^Xw^X!b^X!c^X~OvkO!akO~OvnOtcXwcX~OtpO~OwqO~OvkO!akO!bbO!cbO~OZ_ao_av_a!a_at_aw_a!b_a!c_a~P!OOZiOo^av^a!a^at^aw^a!b^a!c^a~OvnOtcawca~OZ_io_iv_i!a_it_iw_i!b_i!c_i~P!OO",
  goto: "$}oPPPPPPPPPPPPPpt!V!c!p!{#^!{!{#d#s#z$T$Z$a$g$m$wTZO[SYO[S]QRQdTQynR{r^XOQRT[nrRwi`VOQRT[inrRhWcUOQRTW[inrbUOQRTW[inrXeVghvQ_QRaRkTOQRTVW[ghinrvQlZTrdsQcTQtdR}sXfVghvQ[ORm[Qo]RzoQsdR|sQgVSugvRvhQjXRxj",
  nodeNames: "⚠ Number String BacktickString Regex Comment SystemFunction OuterIdentifier SystemIdentifier Identifier Placeholder Operator Program Statement Expression Operand Primary SelfReference Group ExpressionList Array Container BraceOpen Separator BraceClose Postfix",
  maxTerm: 65,
  skippedNodes: [0,5],
  repeatNodeCount: 5,
  tokenData: "(v~RdX^!apq!atu#Uxy#cyz#h|}#m!]!^#r!}#O#w#P#Q#|#o#p$R#p#q(f#q#r(q#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~!fYq~X^!apq!a#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~#ZPr~tu#^~#cOs~~#hOu~~#mOt~~#rOv~~#wO!a~~#|Ox~~$ROw~~$Wb!`~qr%`st%etu%jvw%oz{%z{|&P!O!P&^!P!Q&i![!]&t!]!^&y!^!_'O!_!`'Z!`!a'`!a!b'm!b!c'r#O#P'w#Q#R(S#p#q(X~%eO!U~~%jO!P~~%oO!T~~%rPvw%u~%zO!X~~&PO!W~~&UP!V~{|&X~&^O!]~~&aP!O!P&d~&iO!Q~~&lP#O#P&o~&tO![~~&yO}~~'OO{~~'RP!^!_'U~'ZO!^~~'`Oy~~'eP!R~!`!a'h~'mO!_~~'rOz~~'wO!O~~'zP!P!Q'}~(SO!Z~~(XO!S~~(^P|~#p#q(a~(fO!Y~~(iP#q#r(l~(qO!b~~(vO!c~",
  tokenizers: [rixTokens, 0],
  topRules: {"Program":[0,12]},
  tokenPrec: 0
})
