import { createWidgetSession } from "../../src/tools/widget-session.js";
import { expect, test } from 'bun:test';
import { appendRixCelEvent as append, createRixCelDocument as create, parseRixCelDocument, setRixCelCursor, parseAndEvaluate, formatValue, stringifyRixCelDocument, Context, rixCelCellFormat, createSheet, renderOutputHtml, formatOutputText } from '../../src/index.js';
import { replayRixCelDocument as replay } from '../../src/runtime/rixcel-document.js';
const options = document => { const context = new Context(); context.setFresh('hosttext',{type:'string',value:stringifyRixCelDocument(document)}); return {context}; };
const region = (document, name, start, end) => append(document,{type:'view:region',name,start,end});
const style = (document, start, end, style) => append(document,{type:'view:format',start,end,style});
test('rank-N regions and layered formatting stay sparse, replay, branch and follow insertion',()=>{
 let d = create({id:'regions',shape:[1000000,1000000,3]});
 d = region(d,'Totals',[2,2,2],[7,9,3]);
 d = style(d,[2,2,2],[7,9,3],{bold:true,color:'#123456',numberFormat:'decimal',precision:2});
 d = style(d,[3,3,2],[4,4,2],{bold:null,italic:true});
 const saved=d;
 expect(replay(d).slots).toHaveLength(0);
 expect(rixCelCellFormat(replay(d).view,[3,3,2])).toEqual({color:'#123456',numberFormat:'decimal',precision:2,italic:true});
 expect(rixCelCellFormat(replay(d).view,[3,3,1])).toEqual({});
 d=append(d,{type:'axis:insert',axis:1,coordinate:4,count:2});
 d=append(d,{type:'axis:insert',axis:3,coordinate:1,count:1});
 expect(replay(d).view.regions.Totals).toEqual({start:[2,2,3],end:[9,9,4]});
 expect(rixCelCellFormat(replay(d).view,[5,3,3]).italic).toBe(true);
 const undone=setRixCelCursor(d,saved.cursor);expect(replay(undone).view).toEqual(replay(saved).view);
 expect(replay(setRixCelCursor(parseRixCelDocument(JSON.stringify(undone)),d.events.length)).view).toEqual(replay(d).view);
 const removed=region(undone,'Totals',null,null);expect(replay(removed).view.regions).toEqual({});
 expect(removed.events.some(e=>e.type==='axis:insert')).toBe(false);
 expect(JSON.stringify(d).length).toBeLessThan(3000);
});
test('regions and style validation rejects malformed bounds and executable styling atomically',()=>{
 const d=create({shape:[3,4,2]});const before=JSON.stringify(d);
 for(const [a,b] of [[[0,1,1],[2,2,2]],[[2,1],[3,2]],[[3,1,1],[2,2,2]],[[1,1,1],[4,2,2]]]) expect(()=>region(d,'Good',a,b)).toThrow();
 for(const name of ['','not a name','__proto__','x'.repeat(65)]) expect(()=>region(d,name,[1,1,1],[2,2,2])).toThrow();
 for(const bad of [{color:'red;position:absolute'},{background:'url(javascript:alert(1))'},{font:'x'},{bold:'true'},{precision:21},{numberFormat:'js'}]) expect(()=>style(d,[1,1,1],[2,2,2],bad)).toThrow();
 expect(JSON.stringify(d)).toBe(before);
 const full=create({shape:[1],view:{regions:Object.fromEntries(Array.from({length:256},(_,i)=>[`Region${i}`,{start:[1],end:[1]}]))}});
 expect(()=>region(full,'Extra',[1],[1])).toThrow('256');
 expect(Object.keys(replay(full).view.regions)).toHaveLength(256);
 expect(()=>create({shape:[2,2],view:{regions:{Bad:{start:[2,2],end:[1,1]}}}})).toThrow();
});
test('canonical region and format commands execute, preserve history and exact values in display',()=>{
 let d=create({id:'display',shape:[2,2]});
 d=append(d,{type:'slot:set',index:[1,1],source:'1/3'});
 const base=d;
 d=region(d,'Summary',[1,1],[2,2]);
 d=style(d,[1,1],[2,2],{bold:true,italic:true,background:'#123456',align:'right',numberFormat:'decimal',precision:2});
 const commands=d.events.slice(base.cursor).map(e=>e.command).join(';');
 const result=parseAndEvaluate(`document:=.RiXCelImport(hosttext);${commands};[document,.RiXCelExport(document)]`,options(base)).values;
 expect(formatValue(result[0].get([1,1]))).toBe('1/3');
 expect(replay(parseRixCelDocument(result[1].value)).view).toEqual(replay(d).view);
 const output=createSheet([result[0]]); const html=renderOutputHtml(output,formatValue);
 expect(html).toContain('font-weight:bold');expect(html).toContain('background-color:#123456');expect(html).toContain('≈ 0.33');
 const session=createWidgetSession(output);session.dispatch({type:'sheet:formula',index:[1,1],source:'2/3'});expect(session.cellUpdates(formatValue)[0].text).toBe('≈ 0.67');session.dispose();
 expect(html).toContain('data-rix-address="grid[1,1]"');expect(formatOutputText(output,formatValue)).toContain('≈ 0.33');
 const deleted=region(d,'Summary',null,null).events.at(-1).command;
 const deletedResult=parseAndEvaluate(`document:=.RiXCelImport(hosttext);${deleted};.RiXCelExport(document)`,options(d));
 expect(replay(parseRixCelDocument(deletedResult.value)).view.regions).toEqual({});
});
